### ISSUE TITLE
My starship config for bartib.

### ISSUE THREAD

**Issue by berkes** [nikolassv/bartib#30]
Hi,

Thanks for the great software! Very much appreciated that you put it out there!

I'm not sure where I can put this, so I'll leave it in a ticket for now. Let me know if you want it in a special place and I'll whip up a PR.

I'm using [starship](https://starship.rs) to fancyfy my console. I've added starship to that, and thought maybe others can benefit too.

![image](https://github.com/nikolassv/bartib/assets/77059/4a70ea46-9476-4c93-800a-4593fb8b4348)

I thought I'd share my setup. It's simple but wiring up required some trial-and-error, grep/pipe stuff.

The idea is simple, just add a [custom command](https://starship.rs/config/#custom-commands) to starship.toml config.

```
[custom.bartib]
style = "bg:#06969A"
format = "[$symbol ($output) ]($style)"
command = "bartib current | head -n 3 | tail -n 1 | tr -d '\n'"
when = "bartib current | grep -q -v 'No Activity is currently running'"
symbol = "⏲️ "
```

Then use it in the prompt somewhere. E.g.:
format = """
.... your other format strings.... |${custom.bartib} >
"""
```

What it does is ugly. And I'll clean it up once I can propose some features to bartib ;).
* Get the first running current item from the table. Using head/tail to just get line 3 and trim newlines.
* But only if we have a running task. Check this by grepping for the placeholder text and using its exit code (0 if placeholder text was not found).

Hope it helps someone. Feel free to close if this is not needed or wanted.

**Comment by dj8yfo** [comment]
this is pretty awesome, just the thing i was looking for, should definetely be added to documentation as a standard recipe

**Comment by lutzzdias** [comment]
After messing around with chatGPT, having @berkes command as the starting point, I was able to get the following command:
`command = "bartib current | head -n 3 | tail -n 1 | sed 's/[[:space:]]\\{2,\\}/ /g' | awk '{print $4, \"-\", $5}'"`

head and tail serve the same purpose, sed removes the whitespace between items, keeping only 1 space and awk is used to get only specific values.

Where:
- $1 -> started date
- $2 -> started time
- $3 -> description
- $4 -> project
- $5 -> time spent

My command will result in:
`{project} - {time}'

But you could edit the awk part in order to customize it
e.g `awk '{print $4 \",\", $3, \"-\", $5}'` = `{project}, {description} - {time}`

In the end, my starship config was the following:
```toml
[custom.bartib]
format = '[󰥔  $output]($style) '
style = "bold #a9b1d6"
command = "bartib current | head -n 3 | tail -n 1 | sed 's/[[:space:]]\\{2,\\}/ /g' | awk '{print $4, \"-\", $5}'"
when = "bartib current | grep -q -v 'No Activity is currently running'"
```

which resulted in:

<img width="138" alt="image" src="https://github.com/nikolassv/bartib/assets/80894260/328d9f5f-9089-4836-86a7-0671694bc359">

**Comment by f00wl** [comment]
Thx for the hack!

As I use multiple words (with spaces) for description I had to tweak the command. This is needed for more than one hour activity to.
Also I used `sh` as shell to speed up the command as explained in [this workaround](https://github.com/starship/starship/issues/4341#issuecomment-1236185930)

```toml
[custom.bartib]
format = '[󰥔 $output]($style) '
style = "#767676"
command = "bartib current | sed -n '3p' | cut -d' ' -f'3-' | sed -E 's/\\xC2\\xA0+//g; s/[^,](([0-9]+h )?<?[0-9]+m)/,\\1/; s/ ([^ ]+),/,\\1,/' | awk -F',' '{print $3, \"[\"$2\"]\", $1}'"
shell = ["sh", "--norc"]
when = "bartib current | grep -q -v 'No Activity is currently running'"
```

Result in:

![Image](https://github.com/user-attachments/assets/38489c0b-291b-4c64-919e-839155d65b56)
